apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: "clickhouse"
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:latest
        ports:
        - containerPort: 9000
          name: native
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/config.d
      volumes:
      - name: clickhouse-config
        configMap:
          name: clickhouse-config
  volumeClaimTemplates:
  - metadata:
      name: clickhouse-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  custom-config.xml: |
    <yandex>
        <listen_host>::</listen_host>
        <listen_try>1</listen_try>
    </yandex>
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
    - port: 9000
      targetPort: 9000
      name: native
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-nodeport
spec:
  selector:
    app: clickhouse
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30900
      name: native
